jwt:
  secret-key: ${JWT_SECRET_KEY:X7v9y$B&E)H@McQfTjWnZr4u7x!A%D*G-}
  expiration-time: 86400000

spring:
  application:
    name: uniSync-api
  security:
    user:
      name: none
      password: none
